#!/usr/bin/env 
# =========================================
# This script performs the BWAS pattern-similarity step.
#
# It takes the IDP-wise HCP brain-behavior association vectors generated by
# 01_compute_hcp_idp_behavior_asso.R, aligns them to the UKB CCA brain-loading
# and computes cross-dataset Spearman correlations. 
# =========================================
from __future__ import annotations

import argparse
import csv
import os
from dataclasses import dataclass
from pathlib import Path

import pandas as pd
from scipy.stats import pearsonr, spearmanr


DEFAULT_REPO_ROOT = Path(os.environ.get("BWAS_PRS_PROJECT_ROOT", Path(__file__).resolve().parents[4]))


@dataclass(frozen=True)
class PhenotypeSpec:
    code: str
    title: str


MODE_PHENOTYPES = {
    "mode1": (
        PhenotypeSpec("Loneliness_Unadj", "Loneliness"),
        PhenotypeSpec("FearAffect_Unadj", "Fear affect"),
        PhenotypeSpec("SSAGA_Agoraphobia", "Agoraphobia"),
        PhenotypeSpec("SSAGA_Depressive_Ep", "Depressive episodes"),
    ),
    "mode2": (
        PhenotypeSpec("ASR_Attn_Raw", "Attention Problems"),
        PhenotypeSpec("ASR_Aggr_Raw", "Aggressive Behavior"),
        PhenotypeSpec("DDisc_AUC_200", "Impulsivity"),
        PhenotypeSpec("AngAffect_Unadj", "Anger Affect"),
    ),
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Align HCP IDP-behavior association vectors with UKB CCA loadings "
            "and compute BWAS pattern-similarity statistics."
        )
    )
    parser.add_argument("--repo-root", default=str(DEFAULT_REPO_ROOT))
    parser.add_argument("--mode", choices=("mode1", "mode2"), required=True)
    parser.add_argument("--hcp-vector-dir", default="")
    parser.add_argument("--ukb-loading-file", default="")
    parser.add_argument("--output-dir", default="")
    return parser.parse_args()


def default_hcp_vector_dir(repo_root: Path, mode: str) -> Path:
    if mode == "mode1":
        return (
            repo_root
            / "results"
            / "BWAS层面验证"
            / "IDP_Bhv"
            / "cross_dataset_compare"
            / "mode1abssort_threshold"
            / "ukb_trauma_vs_hcp_mentaldistress_mode1abssort_broadercov"
            / "aligned_hcp_targets"
        )
    return (
        repo_root
        / "results"
        / "BWAS层面验证"
        / "IDP_Bhv"
        / "cross_dataset_compare"
        / "mode2abssort_threshold"
        / "ukb_mania_vs_hcp_mentaldistress_plus_maniacore_mode2abssort_broadercov"
        / "aligned_hcp_targets"
    )


def default_loading_file(repo_root: Path, mode: str) -> Path:
    return (
        repo_root
        / "results"
        / "BWAS层面验证"
        / "visualization_handoff"
        / "visualization_delivery_2026-05-01"
        / f"{mode}_abssort_selected"
        / f"00_{mode}_cca_loadings"
        / "data"
        / "aligned_tables"
        / "aligned_ukb_baseline.csv"
    )


def default_output_dir(repo_root: Path, mode: str) -> Path:
    return (
        repo_root
        / "results"
        / "github_release_fig8_bwas_prs_pipeline_20260516"
        / "outputs"
        / "bwas_pattern_similarity"
        / mode
    )


def load_hcp_vector(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(path)
    df = pd.read_csv(path)
    required = {"score_trait", "r", "lm_t"}
    missing = sorted(required - set(df.columns))
    if missing:
        raise ValueError(f"{path} is missing required columns: {missing}")
    return df


def align_to_loading(hcp: pd.DataFrame, loading: pd.DataFrame) -> pd.DataFrame:
    # Most current HCP vector tables already carry the aligned UKB loading
    # columns. If not, merge them in using stable IDP identifiers.
    if "cca_weight" in hcp.columns and "hcp_score_trait" in hcp.columns:
        merged = hcp.copy()
    else:
        join_cols = ["hcp_score_trait", "selection_rank"]
        if not set(join_cols).issubset(hcp.columns) or not set(join_cols).issubset(loading.columns):
            raise ValueError(
                "Cannot align HCP vector to loading table. Expected either an HCP table "
                "with cca_weight/hcp_score_trait or both tables containing hcp_score_trait "
                "and selection_rank."
            )
        merged = loading.merge(
            hcp,
            on=join_cols,
            how="inner",
            suffixes=("_ukb", "_hcp"),
        )

    keep = merged[["r", "lm_t", "cca_weight"]].dropna()
    if len(keep) < 3:
        raise ValueError("Too few complete IDPs after alignment.")
    return merged


def compute_stats(merged: pd.DataFrame) -> dict[str, str]:
    plot_df = merged[["r", "lm_t", "cca_weight"]].dropna().copy()
    x = plot_df["r"].astype(float)
    y = plot_df["cca_weight"].astype(float)
    pr, pp = pearsonr(x, y)
    sr, sp = spearmanr(x, y)
    return {
        "n_idp": str(len(plot_df)),
        "pearson_r": f"{float(pr):.6f}",
        "pearson_p": f"{float(pp):.6e}",
        "spearman_rho": f"{float(sr):.6f}",
        "spearman_p": f"{float(sp):.6e}",
    }


def main() -> None:
    args = parse_args()
    repo_root = Path(args.repo_root).resolve()
    hcp_dir = Path(args.hcp_vector_dir).resolve() if args.hcp_vector_dir else default_hcp_vector_dir(repo_root, args.mode)
    loading_file = Path(args.ukb_loading_file).resolve() if args.ukb_loading_file else default_loading_file(repo_root, args.mode)
    out_dir = Path(args.output_dir).resolve() if args.output_dir else default_output_dir(repo_root, args.mode)
    merged_dir = out_dir / "merged_scatter_source_data"
    merged_dir.mkdir(parents=True, exist_ok=True)

    loading = pd.read_csv(loading_file)
    rows: list[dict[str, str]] = []

    for spec in MODE_PHENOTYPES[args.mode]:
        hcp_file = hcp_dir / f"results_{spec.code}.csv"
        hcp = load_hcp_vector(hcp_file)
        merged = align_to_loading(hcp, loading)
        merged_path = merged_dir / f"{spec.code}_r_merged.csv"
        merged.to_csv(merged_path, index=False)
        rows.append(
            {
                "mode": args.mode,
                "phenotype_code": spec.code,
                "panel_title": spec.title,
                "hcp_vector_file": str(hcp_file),
                "ukb_loading_file": str(loading_file),
                "merged_csv": str(merged_path),
                **compute_stats(merged),
            }
        )

    summary_path = out_dir / "bwas_pattern_similarity_summary.csv"
    with summary_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)

    print(f"Wrote merged BWAS scatter source data to: {merged_dir}")
    print(f"Wrote pattern-similarity summary to: {summary_path}")


if __name__ == "__main__":
    main()
